language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ifis' ]; then cd .. && eval "mv $currentfolder generator-ifis" && cd generator-ifis; fi

